# -*- coding: utf-8 -*-
"""Classification+Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KQXlCRSHJka15--i9wE97vQKsbktl25f
"""

from numpy import where
from collections import Counter
from sklearn.datasets import make_blobs
from matplotlib import pyplot as plt

x,y = make_blobs(n_samples=1000, centers=2, n_features=2, random_state=1)
print(x.shape, y.shape)
counter = Counter(y)
print(counter)
for i in range(10):
  print(x[i], y[i])

for label, _ in counter.items():
  row = where(y == label)[0]
  plt.scatter(x[row,0], x[row,1], label = str(label))
plt.legend()
plt.show()