# -*- coding: utf-8 -*-
"""Understanding more about Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc96fU_p0o72H4GDxUr8_3mDY_d-8N5l
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Titanic = pd.read_csv(r"/content/Titanic Dataset.csv")
Titanic.head()

con1 = pd.concat([Titanic['Pclass'],Titanic['Age']])
print(con1.head())

null = Titanic.isnull()
sns.heatmap(null, cmap = 'spring')

dummy1 = pd.get_dummies(Titanic['Gender']).head()
print(dummy1)

dummy2 = pd.get_dummies(Titanic["Embarked"]).head()
print(dummy2)

dummy3 = pd.get_dummies(Titanic["Pclass"]).head()
print(dummy3)

sns.heatmap(Titanic.isnull(), cbar = False)
plt.show()